---
id: droonga-meetup-1
base_name: introduction
tags:
- droonga
- groonga
presentation_date: 2014/7/30
version: 2014.07.31
licenses: []
slideshare_id: droonga-meetup1introduction 
speaker_deck_id: 
ustream_id: 
vimeo_id: 
youtube_id: 
author:
  markup_language: :markdown
  name: 結城洋志
  email: yuki@clear-code.com
  rubygems_user: Piro
  slideshare_user: pirooutsiderreflex
  speaker_deck_user: 
